//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheButlerV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Recipe_ID { get; set; }
        public string Recipe_Name { get; set; }
        public string Recipe_ingredince { get; set; }
        public string Recipe_Instructions { get; set; }
        public Nullable<int> Recipe_types { get; set; }
        public string Recipe_photo { get; set; }
    }
}
